name: CI/CD for seminar-demo

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout seminar-code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t mrfour4uit/seminar-demo:${{ github.sha }} .
        docker push mrfour4uit/seminar-demo:${{ github.sha }}

    - name: Checkout seminar-gitops repo
      uses: actions/checkout@v3
      with:
        repository: mrfour4/seminar-gitops
        token: ${{ secrets.PERSONAL_TOKEN }}
        path: seminar-gitops

    - name: Update Helm values.yaml with new image tag
      run: |
        sed -i "s/tag: .*/tag: ${{ github.sha }}/" seminar-gitops/nextjs/values.yaml

    - name: Commit and Push to seminar-gitops
      run: |
        cd seminar-gitops
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add nextjs/values.yaml
        git commit -m "Update image tag to ${{ github.sha }}"
        git push
