name: Block PR without approval

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    check-approval:
        runs-on: ubuntu-latest
        steps:
            - name: Check PR approvals
              uses: actions/github-script@v6
              with:
                  script: |
                      const pr = await github.rest.pulls.get({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: context.payload.pull_request.number,
                      });

                      const reviews = await github.rest.pulls.listReviews({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: pr.data.number,
                      });

                      const approved = reviews.data.some(
                        r => r.state === "APPROVED" && r.user.login === "mrfour4"
                      );

                      if (!approved) {
                        core.setFailed("❌ PR chưa được @mrfour4 duyệt nên không thể merge.");
                      }
